### ISSUE TITLE
Balances missing object or command

### ISSUE THREAD

**Issue by cheryllayne** [ifrotz/iosfrotz#262]
[Please glance at the existing issues to make sure the problem you are
reporting  isn't a known issue before reporting.  Feel free to remove or
edit any parts of the form template which don't apply to your issue.]
D

What steps will reproduce the problem?
1. \learn lleps
2. \learn mortin
3. these commands output: "Your training is such that you can only memories such a spell with the aid of a spell book containing it.

What is the expected output or behavior?  What do you see instead?
There should be some way to learn the spells in the grimoire, but there isn't. I found an online walkthrough that assumes you can learn them from the book, but the game wants you to copy them to a scroll, and then to use the gnusto spell to transfer them from the scroll to your spell book. There aren't any extra scrolls in the game. The game can't be finished without using the lleps spell.

What version of Frotz are you using?
1.7.1

What device model are you using (e.g., iPhone 6, iPad 4, iPod Touch 4th gen.)
iPad -- newest one

What version of iOS?  (6.1, 7.0, etc.)
8.3

Please provide any additional information below.

**Comment by PeterPiers** [comment]
Having checked that myself, I only get that message if I'm not carrying the grimoire (which makes sense). If I'm carrying the grimoire, I can learn those spells. Is that also the case for you? If you are carrying the grimoire and try to learn them, do you still get that message?

Maybe the walkthrough you found skipped the step where you pick up the book. Could you please link to it so I could check that as well?

**Comment by cheryllayne** [comment]
Thanks for the quick response. I mean, I checked the walkthrough at the
point when I had the elephant, and it allowed me to *read* the grimoire,
which would be odd if I weren't holding it, but perhaps it's still in the
box. Thanks very much! Nice work on the games.

Cherie

On Friday, July 3, 2015, PeterPiers <notifications@github.com> wrote:

> Having checked that myself, I only get that message if I'm not carrying
> the grimoire (which makes sense). If I'm carrying the grimoire, I can learn
> those spells. Is that also the case for you? If you are carrying the
> grimoire and try to learn them, do you still get that message?
>
> Maybe the walkthrough you found skipped the step where you pick up the
> book. Could you please link to it so I could check that as well?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ifrotz/iosfrotz/issues/262#issuecomment-118302369>.
>


-- 
Sent from my telephone

**Comment by cheryllayne** [comment]
Yep. That was the issue. Thanks!
