### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by Challion** [ifrotz/iosfrotz#271]
[Please glance at the existing issues to make sure the problem you are
reporting  isn't a known issue before reporting.  Feel free to remove or
edit any parts of the form template which don't apply to your issue.]
D

What steps will reproduce the problem?
1. Switching between apps
2. Reopening Frotz
3. Entering text prompt

What is the expected output or behavior?  What do you see instead?
n/a

What version of Frotz are you using?
1.7.1

What device model are you using (e.g., iPhone 6, iPad 4, iPod Touch 4th gen.)
iPhone 6

What version of iOS?  (6.1, 7.0, etc.)
8.3

Please provide any additional information below.
I quite enjoyed Frotz, and it makes me sad that it is now very difficult to use due to frequent crashing. Please fix :)

**Comment by spathiwa** [comment]
Dup of #274
