### ISSUE TITLE
Can't delete games in "search results" 

### ISSUE THREAD

**Issue by PeterPiers** [ifrotz/iosfrotz#273]
I often have to delete games to put in newer, updated versions. Currently I can't use the search bar to do this because I can't actually delete them (by swiping left on the name) in the "search results" pane.

So despite having a very nice search bar, I still have to manually go hunt for the game I want. Then I have to play it to delete all the saved games I have. Then I have to leave the game, enter the "I" pane and delete the autosave. Then I can finally delete the game.

This is related to issue 270, of course, but it was just an example of what the whole process looked like. This issue is merely about not being able to delete games I've just searched for.

**Comment by spathiwa** [comment]
Fixed in ed889b6.

**Comment by spathiwa** [comment]
Feature added in 1.8 in App Store.
