### ISSUE TITLE
Too much text on the status line freezes/crashes iFrotz

### ISSUE THREAD

**Issue by PeterPiers** [ifrotz/iosfrotz#275]
I've been reporting this on individual games, and I now realised how much more useful it would be, instead, to open a new issue. It certainly qualifies as a definite bug.

Essentially, too much text on the status line causes iFrotz to hang or crash. Here are the individual reports:

****************
Mortlake Manor (http://ifdb.tads.org/viewgame?id=5acwwdfbclwq9bj4): Go north from the attached savegame (available in the "100%" issue) or type these commands:

e.s.w.get
e.e.e.s.s
e.s.s.w.unlock door
n.n.n.n

...and that's it. Going north from this room either freezes or crashes iFrotz.

I wonder if it has to do with the room's very long name: "Intersection of a North-South Corridor and an East-West Passage" (spoiler. I'm sure it does)
**************
Return to Zork: Another Story (http://ifdb.tads.org/viewgame?id=1b82dexzzu81ero0): Again, one location's name is too big and iFrotz freezes entirely, even if I scale the whole text down to the minumum size before entering the room. The room's name is "[Flying Over the Desert (again and again) - hanging by a vulture]" (brackets included).

(a savegame is included in the "100%" issue)
***************
Plundered Hearts Invisiclues (http://www.waitingforgo.com/invisiclues/plundizm.z5): It's only the InvisiClues, mind, which is a .z5 file made by a third party at www.waitingforgo.com.

Trying to open a hint crashes iFrotz, unless it's in landscape mode and the font is pretty darned small. I think it has to do with the sheer amount of text that ends up in the status bar, those questions are VERY verbose. Regardless, I'm sure iFrotz could deal with that more elegantly than crashing. ;)

****************
Pytho's Mask (http://ifdb.tads.org/viewgame?id=spsnevz1br6f2z3v): The ZCode version has a problem which is actually the same as the Plundered Hearts invisiclue above. The game tries to print a LOT of text into the status bar (type "z" a few times), and it just crashes.
*****************
Revenger (http://ifdb.tads.org/viewgame?id=mr67fiyrvgai97ms): Same bug: too much text in the status bar. This time it's the Hint system. Type "hints" (twice) to get to the hint system, select the first cathegory. Some of those options freeze iFrotz because it's too much text. Even if I reduce the size to the unreadable minimum.

**Comment by spathiwa** [comment]
Fixed in a1ea932.

**Comment by spathiwa** [comment]
Fixed in 1.8 in App Store.
