### ISSUE TITLE
Can't access iFrotz with file-managing programs any more

### ISSUE THREAD

**Issue by PeterPiers** [ifrotz/iosfrotz#277]
I use iMazing to transfer games to and from my iPod. I put them in FileApp, a very nice file-managing app with an Explorer-like structure of folders. It works a treat.

I used to also use iMazing to access the save folder of Frotz, so I could transfer my saved games. But it's not possible any more, due to that restriction where you can only access apps with sharing-thingammy enabled.

I'd never seen this before because I'd made a shortcut of the SAVES folder in iMazing, and apparently that bypassed the whole thing! But I had a problem with my iPod, it had to be replaced, and I had to re-register it with iMazing and now I've lost my shortcuts.

I can still use the FIle Transfer thing, but it's nowhere near as convenient.

**Comment by PeterPiers** [comment]
With the File Transfer thing I can no longer add saved games to iFrotz via http (FTP seems to work but it's read-only by default in Forefox and I haven't the patience to hunt for FTP managers right now). It may be because of the sheer number of games I have - their names don't even display. I get a list of PLUS signs at the left of the screen, and clicking them gives me a list of the saved games associated with the game. 

When I click the bit for importing a saved game (I can download them ok), I get the file browser asking for a file upload. I select the file... then nothing happens. I don't even see an "ok" button to confirm and start the process, is there supposed to be one?

**Comment by PeterPiers** [comment]
UPDATE: Having file-sharing turned on fixed the original issue, and my difficulties with FileTransfer were related to some blorbed games having really large images that iFrotz took to be cover images, messing up the spacing. Short of forcing a size for the cover images in the file transfer .html, not much to do or fix there.

**Comment by spathiwa** [comment]
Fixed in d90b2b10.

**Comment by spathiwa** [comment]
Fixed in 1.8 in App Store.
