### ISSUE TITLE
iOS 10: This app has not been updated to 64-bit

### ISSUE THREAD

**Issue by leugengroot** [ifrotz/iosfrotz#278]
I updated my iPhone the the first public beta of iOS10. When you start up Frotz for the first time, you get a messagebox that says "This app has not been updated to 64-bit". Aside from the message, Frotz works pretty much fine under iOS10 so far.

more info can be found here 
http://www.idownloadblog.com/2016/07/07/ios-10-tidbit-64-bit-apps-warning-message/

**Comment by spathiwa** [comment]
Thanks, I'm aware of this and will try to submit a 64-bit version before iOS 10 releases or soon after.

Some of Apple's own apps even give this warning in the beta (such as Remote, if you haven't installed the new beta one).

**Comment by PeterPiers** [comment]
Will there be 32 AND 64 bit versions?

I ask because I'm quite afraid that my own device (iPod Touch 5) may be 32bit, and I have nightmarish visions of iFrotz becoming exclusively 64bit and therefore being unable to be run by me.

**Comment by spathiwa** [comment]
Relax!  The beta you're running already is the version with 64-bit support.  It still supports 32-bit as well.

**Comment by PeterPiers** [comment]
Duly relaxed! :)

**Comment by alanshutko** [comment]
Which version of Xcode will you be targeting?  I've pulled down the source and was thinking about trying to clear out some of the issues.

**Comment by spathiwa** [comment]
I'll build with Xcode 8 and the iOS 10 SDK once it releases, but with an iOS 7 or 8 deployment; I haven't decided whether to drop 7 or not.
What issues are you thinking about looking at?  Several of the recent ones are already fixed, or fixed just by rebuilding from source w/a newer SDK, but I don't typically close issues until I release a version with the fix.

**Comment by alanshutko** [comment]
I had crashes on iOS 10 (which seem like it'll fix with new build).  I was going to also peek at #275 .  

Xcode 8 drops support for iOS 7, so if you want to keep iOS 7 it means Xcode 7.  :(

**Comment by spathiwa** [comment]
They hid it in the Xcode deployment target option ring, but it still works.
You can manually enter 7.0 and it still builds and deploys to an iOS 7 device fine.

**Comment by spathiwa** [comment]
Looks like slightly less than 4% of users in the month of July are on iOS 7 (and about 5% on an even earlier iOS version because their device is too old to upgrade).
My understanding is that users with older devices will be able to download older versions of apps (the newest one which still had support for their device/iOS version), so those users will still be able to run an older Frotz if I drop support.  Users running iOS 7 can upgrade to 8 or 9 if they want, so I will probably drop iOS 7 support anyway.

**Comment by spathiwa** [comment]
Fixed in 429f641 and 4c85f43

**Comment by spathiwa** [comment]
Fixed in 1.8 in App Store.  I did change min required OS to iOS 8.
