### ISSUE TITLE
Folders for better organizing possible?

### ISSUE THREAD

**Issue by leugengroot** [ifrotz/iosfrotz#280]
I carry around a lot of games on my iPhone/iPad. Might it be possible to add some sort of folder-structure or something similar to better organize the files/stories?

Jens

**Comment by PeterPiers** [comment]
FWIW, I used to request this as well. My workaround may work for you - simply, edit the name of the games to look like, for instance, "Adventureland (Scott Adams)", "Suspended (Infocom)" and so on. Possibly "Kerkerkruip (RPG)". Then you can use the search bar to look for Scott Adams, Infocom, or what have you.

It's not as neat as folders, no, but it's a workaround that I've found to work well for me. And trust me, I have a *lot* of games on my iPod as well.
