### ISSUE TITLE
iOS version can't get TADS games from ZIPs - at least, not directly from IFDB

### ISSUE THREAD

**Issue by BiggerJ** [ifrotz/iosfrotz#282]
What steps will reproduce the problem?
1. Go to IFDB within iOS version of Frotz
2. Go to entry for TADS game
3. Download ZIP file cotaining TADS game

What is the expected output or behavior?  What do you see instead?
Expected: runnable game file/s found within ZIP is/are listed and added to game list. Instead: list of found games appears but is blank desides the dialog box's title and button.

What version of Frotz are you using?
1.8

What device model are you using (e.g., iPhone 6, iPad 4, iPod Touch 4th gen.)
iPod Touch 5th gen

What version of iOS?  (6.1, 7.0, etc.)
9.3.5

Edit: Strangely, I tried it again later after noticing that one of my early attempts had actually worked and it successfully pulled TADS game files from ZIPs this time.

**Comment by spathiwa** [comment]
Not sure what was happening before, but App Store Release 1.8.7 also has improved ZIP handling that allows you to select the individual game files to extract/install.
