### ISSUE TITLE
Bring back iTunes File sharing

### ISSUE THREAD

**Issue by KevinBlue18** [ifrotz/iosfrotz#285]
The file transfer protocol should be updated. Because the file transfer protocol is not showing in iTunes.

**Comment by spathiwa** [comment]
(Renamed from original issue which incorrectly called this the 'file transfer protocol')
iTunes File sharing was rejected by Apple in the 1.8 update and had to be removed.
In order for them to allow me to bring it back, I have to move all the internal files Frotz saves in the Documents directory somewhere else, such as Application Support, so only user documents are visible there.

**Comment by spathiwa** [comment]
I'm actually still planning on doing this, it's just more of a lift because of the need to relocate internal files.

**Comment by KevinBlue18** [comment]
I hope to try it out if do get another Apple device in the future.

**Comment by spathiwa** [comment]
iTunes File sharing reenabled in App Store release 1.8.7, commits 924e456f927, a123e59427.
