### ISSUE TITLE
Love the game. Miss these types of adventures.

### ISSUE THREAD

**Issue by greylogan** [ifrotz/iosfrotz#295]
[Please glance at the existing issues to make sure the problem you are
reporting  isn't a known issue before reporting.  Feel free to remove or
edit any parts of the form template which don't apply to your issue.]
D

What steps will reproduce the problem?
1. Downloading on iPad Pro 12.9 2018 version
2.
3.

What is the expected output or behavior?  What do you see instead?
Screen had to be swiped to read the long text instead of having text on one page.
What version of Frotz are you using?
1.7.1

What device model are you using (e.g., iPhone 6, iPad 4, iPod Touch 4th gen.)
iPad Pro 12.9" 2018

What version of iOS?  (6.1, 7.0, etc.)
12.3

Please provide any additional information below.
I was wondering if there will be an update to the game to include an equivalent to word wrap which brings all the text on one page instead of having to swipe the screen to continue reading the text and swiping to go back to the first screen? Doing it this way makes the game rather annoying to play.

**Comment by spathiwa** [comment]
Sorry, I can't figure out what you mean by this.
Which story were you playing in Frotz that has this behavior?  Why would you need to keep going back to a 'first screen'?

**Comment by spathiwa** [comment]
Closing due to lack of info.
