### ISSUE TITLE
Allow larger font sizes

### ISSUE THREAD

**Issue by entonio** [ifrotz/iosfrotz#299]
Hi. Frotz was one of the first apps I installed on my phone, more than a decade ago. I love the app design and simplicity. Unfortunately, even though I keep trying, I've never managed to keep playing for more than a minute, the 24 pt text size is just too small for me, whatever the font. It's something I can cope with in more widget-oriented tasks (such as writing an issue on github), but not at all on a text-centred activity. If you look at the largest font sizes on the Kindle or Wikipedia app, they're far bigger than what we can select here. It's either being able to use at least 28 or 32 or something like that, no matter how it may compromise the amount of text that fits, or no playing at all for me...

**Comment by spathiwa** [comment]
Bumped maximum font size in 1.8.5.
