### ISSUE TITLE
Frotz crashes Dialog-Game

### ISSUE THREAD

**Issue by mikawa** [ifrotz/iosfrotz#302]
There seems to be a bug when running game compiled with Dialog from Linus Akesson to z-code which uses non-ASCII chracters. I've made some small examples in german, and when i type
"erz"
like the first letter of "erzähl .... lucas von mir" frotz crashes at typing the "z"
i've only found this combination to crash, no other combination can seemingly do it, and you have to type this in non-capital letters.

**Comment by spathiwa** [comment]
I'm finally getting around to working on a bug fix update to Frotz.  Do you have a game file you can attach or link which demonstrates this issue?

**Comment by spathiwa** [comment]
I fixed a bunch of Unicode issues which may have addressed this issue, but I cannot tell without a reproducing game file.

Closing this for now, re-open if you can provide a use case and it's still happening in Frotz 1.8.7 or later.
