### ISSUE TITLE
Notes Text Color Issue

### ISSUE THREAD

**Issue by kennsnipes** [ifrotz/iosfrotz#306]
The background in Notes is white. The text in Notes is white. I can’t see the text in Notes.

Aside from that, Frotz is amazing. I hope you support more formats soon! Thank you so much!

**Comment by spathiwa** [comment]
Well, how about that.  Looks like I never tested Notes in Dark mode when I updated the SDK to support it.  Sorry about that.
As a workaround, you can temporarily switch to Light mode in settings while playing Frotz.  

What formats are you hoping for in particular?

**Comment by kennsnipes** [comment]
All the Adrift stuff would be great! 

Thank you so much for this app. There’s nothing else like it.

-KS
>

**Comment by spathiwa** [comment]
Fixed in 1.8.5.
