### ISSUE TITLE
Does Frotz's functionality to download new games to add to its Story List still work correctly?

### ISSUE THREAD

**Issue by aubloom** [ifrotz/iosfrotz#318]
I'm using Frotz 1.8.6 on an iPhone 12 mini. I recall that in the past (on an older version), if I used Safari to visit the direct link to a story file (out in the 'wild') recognised by Frotz, an offer would appear to download this and/or move it to Frotz / open it in Frotz. And then that game would join the story list.

I tried this the other day, and a message appeared asking me if I wanted to download the game. I confirmed I did, but then the file didn't go to Frotz. It didn't go anywhere visible, which makes me think perhaps it just went to my iCloud drive or something, courtesy of ios?

If I use Frotz's own IFDB browsing functionality, game files accessed that way work fine. They enter Frotz and join the story list. So that's good. But for files in the wild, I don't know if something has changed in Frotz, or if Frotz's story-downloading functionality has simply being usurped/blocked by Apple's OS. I used this 'in the wild' functionality to allow people to play a game I sell commercially - they were able to get it into Frotz by visiting its download page in Frotz. But it looks like this method doesn't work at the moment.  Thanks.

**Comment by spathiwa** [comment]
Thanks for reporting this.  Updates in iOS seem to have broken this. I'll investigate what I can do to reenable it.

**Comment by ifrotz** [comment]
Finally getting back to this, sorry for delay.

So, for me, the functionality still works, it's just more convoluted, so you'll probably need to give your users more detailed instructions on your download page.

You can download a story file from an arbitrary web site in Safari, and then after the "Do you want to download <story file>?" prompt, it downloads to phone storage or iCloud drive by default and, like you said, doesn't offer to open the file in any apps automatically.  However, you can press the menu glyph in the URL bar to see downloads; it's the  'Aa' symbol, and will also have a blue download arrow symbol next to it showing there are recent downloads).  The menu contains a "Downloads" item, which will take you to the downloaded file sheet with the story file listed.  From there you can press the "Send to" button (box with an up arrow coming out of it) and send it to Frotz.   Please let me know if this does not work for you.

**Comment by aubloom** [comment]
Thanks for the details. I couldn't find the 'Aa', but maybe that's because I'm an old iPad using an old ios (12.5.7) - but that didn't matter. Even without the 'Aa', after downloading the gblorb one way or another, I was able to find it using the Files app, browse tab, then clicking the file and using the Share button to send to Frotz. Thanks much!
